# Convolutional Neural Networks(CNNs)

## Introduction

Convolutional Neural Networks are a type of Deep Learning Algorithm that is used for image recognition and classification. They are also used for other tasks like object detection, image generation, etc. 

卷积神经网络是一种用于图像识别和分类的深度学习算法。它们也用于其他任务,如目标检测、图像生成等。

CNNs are inspired by the structure of the human brain. The brain has a visual cortex that is responsible for processing visual information. The visual cortex has a small region of cells that are sensitive to specific regions of the visual field. This region is called the receptive field. The receptive fields of different cells overlap to cover the entire visual field. The cells in the visual cortex are sensitive to different features of the visual field like edges, colors, etc.

CNN受到人脑结构的启发。人脑有一个负责处理视觉信息的视觉皮层。视觉皮层有一个对视觉场的特定区域敏感的小区域。这个区域被称为感受野。不同细胞的感受野重叠,覆盖整个视觉场。视觉皮层的细胞对视觉场的不同特征敏感,如边缘、颜色等。

CNNs utilize a special type of layer, aptly named a convolutional layer, that makes them well-positioned to learn from image and image-like data. Regarding image data, CNNs can be used for many different computer vision tasks, such as image processing, classification, segmentation, and object detection.

CNN 利用一种特殊类型的层,即卷积层,使其能够很好地学习图像和类似图像的数据。在图像数据方面,CNN 可用于许多不同的计算机视觉任务,如图像处理、分类、分割和物体检测。

The convolutional layers are the foundation of CNN, as they contain the learned kernels (weights), which extract features that distinguish different images from one another—this is what we want for classification! As you interact with the convolutional layer, you will notice links between the previous layers and the convolutional layers. Each link represents a unique kernel, which is used for the convolution operation to produce the current convolutional neuron's output or activation map.

卷积层是 CNN 的基础,因为它们包含了学习到的核（权重）,这些核可以提取出区分不同图像的特征--这正是我们想要的分类功能！当你与卷积层交互时,你会注意到前几层与卷积层之间的链接。每个链接都代表一个独特的内核,用于卷积操作,生成当前卷积神经元的输出或激活图。

![](https://img-blog.csdnimg.cn/f2fab1646d25417e98c6b23480bf525a.gif#pic_center)

The convolutional neuron performs an elementwise dot product with a unique kernel and the output of the previous layer's corresponding neuron. This will yield as many intermediate results as there are unique kernels. The convolutional neuron is the result of all of the intermediate results summed together with the learned bias.

卷积神经元与唯一的内核和上一层相应神经元的输出进行元素点乘。有多少个独特的内核,就会产生多少个中间结果。卷积神经元是所有中间结果与学习偏置相加的结果。


![](https://poloclub.github.io/cnn-explainer/assets/figures/convlayer_overview_demo.gif)

For example, let's look at the first convolutional layer in the Tiny VGG architecture above. Notice that there are 10 neurons in this layer, but only 3 neurons in the previous layer. In the Tiny VGG architecture, convolutional layers are fully-connected, meaning each neuron is connected to every other neuron in the previous layer. Focusing on the output of the topmost convolutional neuron from the first convolutional layer, we see that there are 3 unique kernels when we hover over the activation map.

例如,让我们来看看上述 Tiny VGG 架构中的第一个卷积层。请注意,这一层有 10 个神经元,而上一层只有 3 个神经元。在 Tiny VGG 架构中,卷积层是全连接的,这意味着每个神经元都与上一层中的其他神经元相连。我们将注意力集中在第一个卷积层最顶端卷积神经元的输出上,当我们将鼠标悬停在激活图上时,会发现有 3 个独特的内核。


The size of these kernels is a hyper-parameter specified by the designers of the network architecture. In order to produce the output of the convolutional neuron (activation map), we must perform an elementwise dot product with the output of the previous layer and the unique kernel learned by the network. In TinyVGG, the dot product operation uses a stride of 1, which means that the kernel is shifted over 1 pixel per dot product, but this is a hyperparameter that the network architecture designer can adjust to better fit their dataset. We must do this for all 3 kernels, which will yield 3 intermediate results.

这些核的大小是网络架构设计人员指定的一个超参数。为了生成卷积神经元的输出（激活图）,我们必须将上一层的输出与网络学习到的唯一核进行元素点乘。在 TinyVGG 中，点乘运算使用的跨距为 1，这意味着每次点乘时，内核都会移动 1 个像素，但这是一个超参数，网络架构设计师可以对其进行调整，以更好地适应自己的数据集。我们必须对所有 3 个内核都这样做，这将产生 3 个中间结果。

![](https://poloclub.github.io/cnn-explainer/assets/figures/convlayer_detailedview_demo.gif)

Then, an elementwise sum is performed containing all 3 intermediate results along with the bias the network has learned. After this, the resulting 2-dimensional tensor will be the activation map viewable on the interface above for the topmost neuron in the first convolutional layer. This same operation must be applied to produce each neuron's activation map.

然后，再对所有 3 个中间结果以及网络学习到的偏置进行元素相加。之后，得到的二维张量将是第一个卷积层最顶层神经元的激活图，可在上述界面查看。在绘制每个神经元的激活图时，都必须执行相同的操作。

With some simple math, we are able to deduce that there are 3 x 10 = 30 unique kernels, each of size 3x3, applied in the first convolutional layer. The connectivity between the convolutional layer and the previous layer is a design decision when building a network architecture, which will affect the number of kernels per convolutional layer. 

通过一些简单的数学运算，我们可以推断出第一卷积层中有 3 x 10 = 30 个独特的内核，每个内核的大小为 3x3。卷积层和上一层之间的连接是构建网络架构时的一个设计决定，这将影响每个卷积层的内核数量。！

## Case Study MNIST-1

In [1]:
import torch 
import torch.nn as nn
from torch.autograd import Variable
import torch.utils.data as data
import matplotlib.pyplot as plt
import torchvision 
 


In [2]:
# Data preprocessing 
# 数据预处理
# transfer the training data to torch type
# 将training data转化成torch能够使用的DataLoader，这样可以方便使用batch进行训练

# set the seed for the random number generator
# reproducible 将随机数生成器的种子设置为固定值，这样，当调用时torch.rand(x)，结果将可重现
 
torch.manual_seed(1) 


In [3]:
# Hyper Parameters
# 超参数

# EPOCH: the number of times the training data is used for training
# 训练迭代次数
EPOCH = 1 

# BATCH_SIZE: the number of samples in one batch
# 分块送入训练器
BATCH_SIZE = 50 

# TIME_STEP: the number of time steps in one batch
# 学习率 learning rate
LR = 0.001 
 


In [4]:
train_data = torchvision.datasets.MNIST(
    root='./mnist/', # 保存位置 若没有就新建
    train=True, # training set
    transform=torchvision.transforms.ToTensor(), # 
    # converts a PIL.Image or numpy.ndarray to torch.FloatTensor(C*H*W) in range(0.0,1.0)
    download=True
)
 
test_data = torchvision.datasets.MNIST(root='./MNIST/')
 


In [5]:
# 如果是普通的Tensor数据，想使用 torch_dataset = data.TensorDataset(data_tensor=x, target_tensor=y)
# 将Tensor转换成torch能识别的dataset
# 批训练， 50 samples, 1 channel, 28*28, (50, 1, 28 ,28)
train_loader = data.DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)

# 使用torch.no_grad()处理测试数据
with torch.no_grad():
    test_x = torch.unsqueeze(test_data.test_data, dim=1).type(torch.FloatTensor)[:2000] / 255.


 
test_y = test_data.test_labels[:2000]



c:\Users\SBH\anaconda3\Lib\site-packages\torchvision\datasets\mnist.py:80: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
c:\Users\SBH\anaconda3\Lib\site-packages\torchvision\datasets\mnist.py:70: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [6]:
 
# 定义网络结构
# 1）class CNN需要·继承·Module 
# 2）需要·调用·父类的构造方法：super(CNN, self).__init__()
# 3）在Pytorch中激活函数Relu也算是一层layer
# 4）需要·实现·forward()方法，用于网络的前向传播，而反向传播只需要·调用·Variable.backward()即可。
# 输入的四维张量[N, C, H, W]
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        # nn.Sequential一个有序的容器，神经网络模块将按照在传入构造器的顺序依次被添加到计算图中执行，
        # 同时以神经网络模块为元素的有序字典也可以作为传入参数
        # nn.Conv2d 二维卷积 先实例化再使用 在Pytorch的nn模块中，它是不需要你手动定义网络层的权重和偏置的
        self.conv1 = nn.Sequential( #input shape (1,28,28)
            nn.Conv2d(in_channels=1, #input height 必须手动提供 输入张量的channels数
                      out_channels=16, #n_filter 必须手动提供 输出张量的channels数
                      kernel_size=5, #filter size 必须手动提供 卷积核的大小 
                      # 如果左右两个数不同，比如3x5的卷积核，那么写作kernel_size = (3, 5)，注意需要写一个tuple，而不能写一个列表（list）
                      stride=1, #filter step 卷积核在图像窗口上每次平移的间隔，即所谓的步长
                      padding=2 #con2d出来的图片大小不变 Pytorch与Tensorflow在卷积层实现上最大的差别就在于padding上
            ), # output shape (16,28,28) 输出图像尺寸计算公式是唯一的 # O = （I - K + 2P）/ S +1
            nn.ReLU(), # 分段线性函数，把所有的负值都变为0，而正值不变，即单侧抑制
            nn.MaxPool2d(kernel_size=2) #2x2采样，28/2=14，output shape (16,14,14) maxpooling有局部不变性而且可以提取显著特征的同时降低模型的参数，从而降低模型的过拟合
        ) 
        self.conv2 = nn.Sequential(nn.Conv2d(16, 32, 5, 1, 2), #output shape (32,7,7)
                                  nn.ReLU(),
                                  nn.MaxPool2d(2))
        # 因上述几层网络处理后的output为[32,7,7]的tensor，展开即为7*7*32的一维向量，接上一层全连接层，最终output_size应为10，即识别出来的数字总类别数
        # 在二维图像处理的任务中，全连接层的输入与输出一般都设置为二维张量，形状通常为[batch_size, size]
        self.out = nn.Linear(32*7*7, 10) # 全连接层 7*7*32, num_classes
        
    def forward(self, x):
        x = self.conv1(x) # 卷一次
        x = self.conv2(x) # 卷两次
        x = x.view(x.size(0), -1) #flat (batch_size, 32*7*7) 
        # 将前面多维度的tensor展平成一维 x.size(0)指batchsize的值
        # view()函数的功能根reshape类似，用来转换size大小
        output = self.out(x) # fc out全连接层 分类器
        return output
# 定义网络结构
 
 


In [7]:
# 查看网络结构
cnn = CNN()
print(cnn) # 使用print(cnn)可以看到网络的结构详细信息，可以看到ReLU()也是一层layer
# 查看网络结构
 
 
# 训练 需要特别指出的是记得每次反向传播前都要清空上一次的梯度，optimizer.zero_grad()
# optimizer 可以指定程序优化特定的选项，例如学习速率，权重衰减等
optimizer = torch.optim.Adam(cnn.parameters(), lr=LR) # torch.optim是一个实现了多种优化算法的包
 
# loss_fun CrossEntropyLoss 交叉熵损失
# 信息量：它是用来衡量一个事件的不确定性的；一个事件发生的概率越大，不确定性越小，则它所携带的信息量就越小。
# 熵：它是用来衡量一个系统的混乱程度的，代表一个系统中信息量的总和；信息量总和越大，表明这个系统不确定性就越大。
# 交叉熵：它主要刻画的是实际输出（概率）与期望输出（概率）的距离，也就是交叉熵的值越小，两个概率分布就越接近
loss_func = nn.CrossEntropyLoss() # 该损失函数结合了nn.LogSoftmax()和nn.NLLLoss()两个函数 适用于分类
 


CNN(
  (conv1): Sequential(
    (0): Conv2d(1, 16, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv2): Sequential(
    (0): Conv2d(16, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (out): Linear(in_features=1568, out_features=10, bias=True)
)


In [8]:
# training loop
for epoch in range(EPOCH):
    for i, (x, y) in enumerate(train_loader):
        batch_x = Variable(x)
        batch_y = Variable(y)
        output = cnn(batch_x) # 输入训练数据
        loss = loss_func(output, batch_y) # 计算误差 #　实际输出，　期望输出
        optimizer.zero_grad() # 清空上一次梯度
        loss.backward() # 误差反向传递 只需要调用.backward()即可
        optimizer.step() # cnn的优化器参数更新
# 训练
 
 


In [9]:
# 预测结果
# cnn.eval()
test_output = cnn(test_x[:10])
pred_y = torch.max(test_output, 1)[1].data.numpy().squeeze()
# torch.max(input, dim)函数  
# torch.max(test_output, 1)[1]  取出来indices 每行最大值的索引
# 输入 input是softmax函数输出的一个tensor  
# 输入 dim是max函数索引的维度0/1，0是每列的最大值，1是每行的最大值
# 输出 函数会返回两个tensor，第一个tensor是每行的最大值；第二个tensor是每行最大值的索引。
# squeeze()函数的功能是：从矩阵shape中，去掉维度为1的。例如一个矩阵是的shape是（5， 1），使用过这个函数后，结果为（5，）。
print(pred_y, 'prediction number')
print(test_y[:10], 'real number')
# 预测结果

[5 0 4 1 9 2 1 3 1 4] prediction number
tensor([5, 0, 4, 1, 9, 2, 1, 3, 1, 4]) real number


## Case Study MNIST-2

In [16]:
import os
import torch
import torch.nn as nn
import torch.utils.data as Data     #小批量
import torchvision                  #提供图像数据集
import matplotlib.pyplot as plt     #绘图
 
#超参数 Hyper Parameters
EPOCH=1
BATCH_SIZE=50
LR=0.001
DOWNLOAD_MNIST=True

In [20]:
#数据下载
if not(os.path.exists('./Data/MNIST'))or not os.listdir('./Data/MNIST'):
    DOWNLOAD_MNIST = True
 
train_data=torchvision.datasets.MNIST(
    root='./Data/MNIST',
    train=True,
    transform=torchvision.transforms.ToTensor(),
    download=DOWNLOAD_MNIST,
)
#展示下载的数据
# print(train_data.train_data.size())                 # (60000, 28, 28)
# print(train_data.train_labels.size())               # (60000)
# plt.imshow(train_data.train_data[2].numpy(), cmap='gray')
# plt.title('%i' % train_data.train_labels[2])
# plt.show()
 


100%|██████████| 9912422/9912422 [00:00<00:00, 28300508.65it/s]


Extracting ./Data/MNIST\MNIST\raw\train-images-idx3-ubyte.gz to ./Data/MNIST\MNIST\raw



100%|██████████| 28881/28881 [00:00<00:00, 29416147.12it/s]


Extracting ./Data/MNIST\MNIST\raw\train-labels-idx1-ubyte.gz to ./Data/MNIST\MNIST\raw



100%|██████████| 1648877/1648877 [00:00<00:00, 25326256.07it/s]


Extracting ./Data/MNIST\MNIST\raw\t10k-images-idx3-ubyte.gz to ./Data/MNIST\MNIST\raw



100%|██████████| 4542/4542 [00:00<?, ?it/s]

Extracting ./Data/MNIST\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./Data/MNIST\MNIST\raw



In [21]:
#小批量数据
train_loader=Data.DataLoader(dataset=train_data,batch_size=BATCH_SIZE,shuffle=True)
 
#选择部分数据训练
 
test_data = torchvision.datasets.MNIST(root='./mnist/', train=False)
test_x = torch.unsqueeze(test_data.test_data, dim=1).type(torch.FloatTensor)[:1000]/255.   # shape from (2000, 28, 28) to (2000, 1, 28, 28), value in range(0,1)
test_y = test_data.test_labels[:1000]
 


c:\Users\SBH\anaconda3\Lib\site-packages\torchvision\datasets\mnist.py:80: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
c:\Users\SBH\anaconda3\Lib\site-packages\torchvision\datasets\mnist.py:70: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [22]:
#搭建网络
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1=nn.Sequential(
            nn.Conv2d(1,16,5,1,2),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.conv2=nn.Sequential(
            nn.Conv2d(16, 32, 5, 1, 2),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )
        self.out=nn.Linear(32*7*7,10)    #全连接层
 
    def forward(self,x):
        x=self.conv1(x)
        x=self.conv2(x)
        x=x.view(x.size(0),-1)
        out=self.out(x)
        return out,x
 
cnn=CNN()
print(cnn)
 


CNN(
  (conv1): Sequential(
    (0): Conv2d(1, 16, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (conv2): Sequential(
    (0): Conv2d(16, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): ReLU()
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (out): Linear(in_features=1568, out_features=10, bias=True)
)


In [23]:
#定义优化器和损失函数
optimizer=torch.optim.Adam(cnn.parameters(),lr=LR)
loss_fun=nn.CrossEntropyLoss()
 


In [25]:
#可视化
from matplotlib import cm
try: from sklearn.manifold import TSNE; HAS_SK = True
except: HAS_SK = False; print('Please install sklearn for layer visualization')
def plot_with_labels(lowDWeights, labels):
    plt.cla()
    X, Y = lowDWeights[:, 0], lowDWeights[:, 1]
    for x, y, s in zip(X, Y, labels):
        c = cm.rainbow(int(255 * s / 9)); plt.text(x, y, s, backgroundcolor=c, fontsize=9)
    plt.xlim(X.min(), X.max()); plt.ylim(Y.min(), Y.max()); plt.title('Visualize last layer'); plt.show(); plt.pause(0.01)
 
plt.ion()
for epoch in range(EPOCH):
    for step,(b_x,b_y) in enumerate(train_loader):
        output=cnn(b_x)[0]
        loss=loss_fun(output,b_y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
 
        if step % 50 == 0:
            test_output, last_layer = cnn(test_x)
            pred_y = torch.max(test_output, 1)[1].data.numpy()
            accuracy = float((pred_y == test_y.data.numpy()).astype(int).sum()) / float(test_y.size(0))
            print('Epoch: ', epoch, '| train loss: %.4f' % loss.data.numpy(), '| test accuracy: %.2f' % accuracy)
            if HAS_SK:
                # Visualization of trained flatten layer (T-SNE)
                tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)
                plot_only = 500
                low_dim_embs = tsne.fit_transform(last_layer.data.numpy()[:plot_only, :])
                labels = test_y.numpy()[:plot_only]
                #plot_with_labels(low_dim_embs, labels)
        plt.ioff()
 
        # print 10 predictions from test data
        test_output, _ = cnn(test_x[:10])
        pred_y = torch.max(test_output, 1)[1].data.numpy()
        print(pred_y, 'prediction number')
        print(test_y[:10].numpy(), 'real number')

Epoch:  0 | train loss: 0.0236 | test accuracy: 0.98
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 9] real number
[7 2 1 0 4 1 4 9 5 9] prediction number
[7 2 1 0 4 1 4 9 5 

## Case Study CIFAR-10

In [37]:
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import torch.nn.functional as F


BATCHSZ=32

cifar_train = datasets.CIFAR10('cifar', True, transform = transforms.Compose([
    transforms.Resize((32,32)),
    transforms.ToTensor()
]), download=True)
cifar_train = DataLoader(cifar_train, batch_size=BATCHSZ, shuffle=True)

cifar_test = datasets.CIFAR10('cifar', False, transform = transforms.Compose([
    transforms.Resize((32,32)),
    transforms.ToTensor()
]), download=True)
cifar_test = DataLoader(cifar_test, batch_size=BATCHSZ, shuffle=True)


x, label = next(iter(cifar_train))
print('x:', x.shape, 'label:', label.shape)


Files already downloaded and verified
Files already downloaded and verified
x: torch.Size([32, 3, 32, 32]) label: torch.Size([32])


In [65]:
# LeNet-5 Version

class LeNet5(nn.Module):

    """
    for CIFAR10 dataset
    """
    def __init__(self):
        super(LeNet5, self).__init__()

        self.model = nn.Sequential(
            # x: [b, 3, 32, 32] => [b, 6, 28, 28]
            nn.Conv2d(3, 6, kernel_size=5, stride=1, padding=0),
            # x: [b, 6, 28, 28] => [b, 6, 14, 14]
            nn.AvgPool2d(kernel_size=2, stride=2, padding=0),
            # x: [b, 6, 14, 14] => [b, 16, 10, 10]
            nn.Conv2d(6, 16, kernel_size=5, stride=1, padding=0),
            # x: [b, 16, 10, 10] => [b, 16, 5, 5]
            nn.AvgPool2d(kernel_size=2, stride=2, padding=0),
            # x: [b, 16, 5, 5] => [b, 120]
            nn.Flatten(),
            nn.Linear(16*5*5, 120),
            nn.ReLU(),
            nn.Linear(120, 84),
            nn.ReLU(),
            nn.Linear(84, 10)
        )
        # use Cross Entropy Loss
        self.criteon = nn.CrossEntropyLoss()


    def forward(self, x):
        # x: [b, 3, 32, 32]
        # out: [b, 10]
        logits = self.model(x)
        #loss = self.criteon(logits, y)
        return logits
    

net = LeNet5()
tmp = torch.randn(2, 3, 32, 32)
out = net(tmp)
print('lenet out:', out.shape)

lenet out: torch.Size([2, 10])


In [66]:
device = torch.device('cuda')
net = LeNet5().to(device)
net.criteon = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(net.parameters(), lr=1e-3)
print(net)

LeNet5(
  (model): Sequential(
    (0): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
    (1): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
    (3): AvgPool2d(kernel_size=2, stride=2, padding=0)
    (4): Flatten(start_dim=1, end_dim=-1)
    (5): Linear(in_features=400, out_features=120, bias=True)
    (6): ReLU()
    (7): Linear(in_features=120, out_features=84, bias=True)
    (8): ReLU()
    (9): Linear(in_features=84, out_features=10, bias=True)
  )
  (criteon): CrossEntropyLoss()
)


In [67]:
for epoch in range(30):
    #设置模式为训练模式
    net.train()

    for batch_idx, (x, label) in enumerate(cifar_train):
        # [b, 3, 32, 32], [b]
        x, label = x.to(device), label.to(device)

        logits = net(x)

        # logits: [b, 10]
        # label: [b]
        # loss: tensor scalar
        loss = net.criteon(logits, label)
        
        # backprop
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch_idx % 100 == 0:
            print('epoch:', epoch, 'batch_idx:', batch_idx, 'loss:', loss.item())
            
    # 设置模式为测试模式
    net.eval()
    with torch.no_grad():   
        # 统计模型在测试集上的表现
        total_num = 0
        total_correct = 0

        for x, label in cifar_test:
            x, label = x.to(device), label.to(device)
            # [b, 3, 32, 32], [b]
            logits = net(x)

            # logits: [b, 10]
            # argmax会返回最大值的索引，即预测的分类
            pred = logits.argmax(dim=1)

            # [b] vs [b] => scalar tensor
            correct = torch.eq(pred, label).float().sum().item()
            total_num += x.size(0)
            total_correct += correct

        acc = total_correct / total_num
        print('epoch:', epoch, 'acc:', acc)

epoch: 0 batch_idx: 0 loss: 2.2910096645355225
epoch: 0 batch_idx: 100 loss: 1.941195011138916
epoch: 0 batch_idx: 200 loss: 1.8169517517089844
epoch: 0 batch_idx: 300 loss: 1.9997152090072632
epoch: 0 batch_idx: 400 loss: 1.909135341644287
epoch: 0 batch_idx: 500 loss: 1.5132193565368652
epoch: 0 batch_idx: 600 loss: 1.9565736055374146
epoch: 0 batch_idx: 700 loss: 1.9035969972610474
epoch: 0 batch_idx: 800 loss: 1.8833225965499878
epoch: 0 batch_idx: 900 loss: 1.8557345867156982
epoch: 0 batch_idx: 1000 loss: 1.524382472038269
epoch: 0 batch_idx: 1100 loss: 1.5075352191925049
epoch: 0 batch_idx: 1200 loss: 1.4421093463897705
epoch: 0 batch_idx: 1300 loss: 1.4827837944030762
epoch: 0 batch_idx: 1400 loss: 1.3112415075302124
epoch: 0 batch_idx: 1500 loss: 1.4391237497329712
epoch: 0 acc: 0.4472
epoch: 1 batch_idx: 0 loss: 1.8201433420181274
epoch: 1 batch_idx: 100 loss: 1.2968909740447998
epoch: 1 batch_idx: 200 loss: 1.737798810005188
epoch: 1 batch_idx: 300 loss: 1.4031187295913696
e

## Resnet

以下是一个resnet的例子，其中是一个resnet的基本单位，也就是一个短接shortcut，

In [ ]:
class Resblk(nn.module):

    # resnet block定义基本的残差块

    def __init__(self,ch_in, ch_out):
        """
        
        """
        super(Resblk, self).__init__()

        self.conv1 = nn.Conv2d(ch_in, ch_out, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(ch_out)

        self.conv2 = nn.Conv2d(ch_out, ch_out, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(ch_out)

        # 新建一个空的extra，如果ch_in != ch_out，就需要对x进行一个线性变换
        self.extra = nn.Sequential()

        if ch_out != ch_in:
            # [b, ch_in, h, w] => [b, ch_out, h, w]
            # 确保x能与F(x)维度相同
            self.extra = nn.Sequential(
                nn.Conv2d(ch_in, ch_out, kernel_size=1, stride=1),
                nn.BatchNorm2d(ch_out)
            )

    def forward(self, x):
        # [b, ch_in, h, w] => [b, ch_out, h, w]
        out = F.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))
        # short cut
        # element-wise add: [b, ch_in, h, w] with [b, ch_out, h, w]
        out = self.extra(x) + out
        return out

这个例子是一个resnet18，所以有4个基本单位，每个基本单位有两个卷积层，所以一共有8个卷积层，最后有一个全连接层，所以一共有9层。

In [ ]:
class ResNet(nn.module):

    def __init__(self):
        super(ResNet, self).__init__()

        self.conv1 = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(64)
        )
        # followed 4 blocks
        # [b, 64, h, w] => [b, 128, h, w]
        